/**:
  ros__parameters:
    port: "/dev/ttyUSB0"
    frame_id: "imu_link"
    publish_tf: true

    sync_period_ms: 10
    sync_sensor_accel: true
    sync_sensor_gyro: true
    sync_sensor_mag: true
    sync_sensor_quaternion: true

    enable_filter: true

    log_level: DEBUG
