/**:
  ros__parameters:
    port: "/dev/ttyUSB0" # iAHRS serial path
                         # iAHRS가 연결된 블럭디바이스 주소를 입력.
                         # Udev Rule 설정을 통해 iAHRS 주소를 특정 주소로 고정시키는것을 권장함.
    frame_id: "imu_link" # 센서 데이터 프레임
    publish_tf: true     # tf publish 여부
                         # base_link -> imu_link로 (0, 0, 0, 0, 0, 0, 1) tf publish

    sync_period_ms: 10           # iAHRS에서 PC로 전송하는 sync 데이터 주기 (ms)
    sync_sensor_accel: true      # 가속도 센서 데이터 활성화 여부
    sync_sensor_gyro: true       # 각속도 센서 데이터 활성화 여부
    sync_sensor_mag: true        # 지자기 센서 데이터 활성화 여부
    sync_sensor_quaternion: true # 쿼터니언 형태의 orientation

    enable_filter: true # iAHRS의 칼만 필터 활성화 여부
                        # sync 데이터의 orientation 등을 얻기 위해서는 활성화 필요.
